name: Build Community Server on Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install prerequisites with Chocolatey
      run: |
        choco install git -y
        choco install nodejs-lts -y
        choco install nuget.commandline -y
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.Net.Component.4.7.2.SDK --add Microsoft.Net.Component.4.7.2.TargetingPack --includeRecommended --includeOptional" -y

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Find solution file
      id: find_sln
      run: |
        $sln = Get-ChildItem -Recurse -Filter CommunityServer.sln | Select-Object -First 1
        if (!$sln) {
          Write-Error "CommunityServer.sln not found"
          exit 1
        }
        echo "Found solution: $($sln.FullName)"
        echo "solution_path=$($sln.FullName)" >> $env:GITHUB_ENV

    - name: Restore NuGet packages
      run: nuget restore $env:solution_path

    - name: Build ONLYOFFICE Community Server
      run: msbuild $env:solution_path /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload build output
      uses: actions/upload-artifact@v4
      with:
        name: community-server-build
        path: |
          **/bin/Release/**
