name: Build and Package ASC Deb

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build solution
        run: msbuild build/msbuild/build.proj /p:Configuration=Release

      - name: Deploy solution
        run: msbuild build/msbuild/deploy.proj /p:Configuration=Release

      - name: Zip DLLs and config files
        shell: pwsh
        run: |
          $files = Get-ChildItem -Recurse -Include *.dll,*.config -File | Where-Object { $_.FullName -like '*\bin\Release\*' }
          Compress-Archive -Path $files.FullName -DestinationPath build-output.zip

      - name: Upload DLLs
        uses: actions/upload-artifact@v4
        with:
          name: community-server-build
          path: build-output.zip

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Windows build artifact
        uses: actions/download-artifact@v4
        with:
          name: community-server-build
          
      - name: Clean modules directory
        run: rm -rf modules

      - name: Unzip DLLs
        run: unzip -o build-output.zip -d modules
          
      - name: Download external DEB if not cached
        if: steps.cache-deb.outputs.cache-hit != 'true'
        run: |
          chmod +x ./build-scripts/download-deb.sh
          ./build-scripts/download-deb.sh
          
      - name: Cache external DEB
        id: cache-deb
        uses: actions/cache@v3
        with:
          path: onlyoffice-desktopeditors.deb
          key: onlyoffice-deb-squeeze-v1

      - name: Extract .deb
        run: |
          chmod +x ./.github/build-scripts/extract-deb.sh
          ./.github/build-scripts/extract-deb.sh onlyoffice-desktopeditors.deb

      - name: Build custom .deb
        run: |
          chmod +x ./.github/build-scripts/build-custom-deb.sh
          ./.github/build-scripts/build-custom-deb.sh extracted-onlyoffice-desktopeditors modules

      - name: Upload rebuilt .deb
        uses: actions/upload-artifact@v4
        with:
          name: rebuilt-deb
          path: onlyoffice-desktopeditors_*.deb
