name: Build and Package Community Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            fakeroot \
            devscripts \
            debhelper \
            dh-make \
            mono-complete

      - name: Restore NuGet packages
        run: |
          nuget restore Studio.sln

      - name: Build solution
        run: msbuild Studio.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Prepare Debian package structure
        run: |
          mkdir -p package/usr/local/bin
          cp -r bin/Release/net5.0/* package/usr/local/bin/
          mkdir -p package/DEBIAN
          echo "Package: community-server" > package/DEBIAN/control
          echo "Version: 1.0.0" >> package/DEBIAN/control
          echo "Architecture: amd64" >> package/DEBIAN/control
          echo "Maintainer: Your Name <your.email@example.com>" >> package/DEBIAN/control
          echo "Description: Community Server Application" >> package/DEBIAN/control

      - name: Build .deb package
        run: |
          dpkg-deb --build package
          mv package.deb ../community-server.deb

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: community-server-deb
          path: community-server.deb
