name: Build Community Server on Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install prerequisites
      run: |
        choco install git -y
        choco install nodejs-lts -y
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.Net.Component.4.7.2.SDK --add Microsoft.Net.Component.4.7.2.TargetingPack --includeRecommended --includeOptional" -y
        refreshenv

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build the solution
      run: |
        cd CommunityServer.sln
        msbuild CommunityServer.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: community-server-build
        path: |
          ./bin
